DROP TABLE IF EXISTS lists CASCADE;

CREATE TABLE lists (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  category_id INTEGER REFERENCES categories(id) ON DELETE CASCADE,
  title VARCHAR(255) NOT NULL,
  status BOOLEAN DEFAULT FALSE,
  timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
